-- Drop and recreate Users table (Example)
DROP TABLE IF EXISTS users
CASCADE;
DROP TABLE IF EXISTS maps
CASCADE;
DROP TABLE IF EXISTS pins
CASCADE;
DROP TABLE IF EXISTS favorites
CASCADE;
CREATE TABLE users
(
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE maps
(
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  description TEXT,
  category VARCHAR(255),
  url TEXT,
  liked INTEGER DEFAULT 0
);
CREATE TABLE pins
(
  id SERIAL PRIMARY KEY NOT NULL,
  latitude DECIMAL(30,20) NOT NULL DEFAULT 0,
  longitude DECIMAL(30,20) NOT NULL DEFAULT 0,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);
CREATE TABLE favorites
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);
